cache: bundler
language: ruby
sudo: false
bundler_args: --without system_tests development
before_install:
- bundle -v
- rm Gemfile.lock || true
- gem update --system
- gem update bundler
- gem --version
- bundle -v
script: "bundle exec rake spec_clean && bundle exec rake validate && bundle exec rake test"
matrix:
  fast_finish: true
  include:
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="3.8.7" STRICT_VARIABLES="yes"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="3.8.7" STRICT_VARIABLES="yes" FUTURE_PARSER="yes"
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
  - rvm: 2.3.4
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 5.0" STRICT_VARIABLES="yes"
  - rvm: 2.3.4
    env: PUPPET_GEM_VERSION="~> 5.0" STRICT_VARIABLES="yes"
notifications:
  email: false
