name: Unit

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    # Items marked as allow_failure=true are allowed to fail
    # This is fixtures using latest untagged versions
    continue-on-error: ${{ matrix.allow_failure }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - ruby: 2.4.10
          puppet: 5
          fixtures: .fixtures.yml
          allow_failure: false
        - ruby: 2.5.8
          puppet: 6
          fixtures: .fixtures.yml
          allow_failure: false
        - ruby: 2.7.2
          puppet: 7
          fixtures: .fixtures.yml
          allow_failure: false
    env:
      BUNDLE_WITHOUT: system_tests:development
      PUPPET_GEM_VERSION: "~> ${{ matrix.puppet }}.0"
      FIXTURES_YML: ${{ matrix.fixtures }}
    name: Puppet ${{ matrix.puppet }} (Ruby ${{ matrix.ruby }} fixtures=${{ matrix.fixtures }})
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          bundler: '2.1.0'
      - name: Validate
        run: bundle exec rake check:symlinks check:git_ignore check:dot_underscore rubocop syntax lint metadata_lint
      - name: Run tests
        run: bundle exec rake parallel_spec